// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Nd4kqUbieZ9dmK2tjsHO5QtOwzzKiP4',
    appId: '1:653962860092:web:3ae31b45b656204d809539',
    messagingSenderId: '653962860092',
    projectId: 'notes-cb808',
    authDomain: 'notes-cb808.firebaseapp.com',
    storageBucket: 'notes-cb808.appspot.com',
    measurementId: 'G-ZM8T8X32M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcG3jgIyGkKg-iNyz6Ea5wXtVtz6ZYRkI',
    appId: '1:653962860092:android:2c8097bde5fc0eaa809539',
    messagingSenderId: '653962860092',
    projectId: 'notes-cb808',
    storageBucket: 'notes-cb808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS6u34ALydiDDzLrGckruuW3w22tdHOaE',
    appId: '1:653962860092:ios:52d5390df74ec4c4809539',
    messagingSenderId: '653962860092',
    projectId: 'notes-cb808',
    storageBucket: 'notes-cb808.appspot.com',
    iosClientId: '653962860092-hpoer6nmumpsmqtcduq1m7bpartemp5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
